services:
  - type: web
    name: ig-notifier-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: PORT
        value: "8000"
      - key: PYTHON_VERSION
        value: "3.11.9"
